[package]
name = "wasm-test"
version = "0.1.0"
authors = ["Anders Lindhardt Madsen <andem20@student.sdu.dk>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
